### ISSUE TITLE
RFC: Add "publish_github_prerelease" add-ons

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-ci-addons#32]
### Overview

This add-on allows to automatically publish pre-release on GitHub. 

A pre-release is identified by a git tag and is associated with one or multiple packages (python wheels, installers, archives, ...)

Project maintainers are responsible to graduate a "pre-release" into "release".

##### Steps

Every day a *bot* will:
* update ITK description and package version in  `ITKPythonPackage` (see details below)
* commit the changes to `ITKPythonPackage`. 

Then, each CI services (or dedicated build bots) will:
* checkout `ITKPythonPackage` source
* build the associated wheels
* use `publish_github_prerelease.py` to publish the generated wheels as pre-release

##### `update_python_version.py` script

This script is not (yet) part of `scikit-ci-addons` and will live in the `ITKPythonPackage` project repository and can be executed as a standalone script. For example, it could then be downloaded and executed by the *bot* named  [kwrobot](https://github.com/kwrobot).

**Usage**

```
Usage:
  python update_python_version.py /path/to/last/ITK/source
```

**Steps**

The *bot* will:
* clone the latest `ITK` source, checkout `nightly-master` branch
* clone `ITKPythonPackage`
* download the script
* execute the script
* commit and push the change to `ITKPythonPackage`

**Script description: update_python_version.py**

Given the patch to both an `ITK` source tree and an `ITKPythonPackage` source tree, the script will:
* get the local commit date of the `HEAD` of [ITK@nightly-master](https://github.com/InsightSoftwareConsortium/ITK/tree/nightly-master). (Using a command like `git show -s --format="%cd" --date=local`)
* get `<major>.<minor>.<patch>` (By extracting the value associated with variables `ITK_VERSION_MAJOR`, `ITK_VERSION_MINOR` and `ITK_VERSION_PATCH` using script like [CMakeParser.py](https://github.com/Slicer/Slicer/blob/eefeac9286f48552e8418a11f412b2823a09b407/Utilities/Scripts/SlicerWizard/CMakeParser.py))
* update [CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/CMakeLists.txt) replacing the ITK version associated with `GIT_TAG` CMake variable to match the latest commit associated with [ITK@nightly-master](https://github.com/InsightSoftwareConsortium/ITK/tree/nightly-master)
* update [setup.py](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/setup.py) by replacing version<sup>1</sup> `<major>.<minor>.<patch>.dev<YYYYMMDD>` where `<major>.<minor>.<patch>` corresponds the ITK release version and `<YYYYMMDD>` corresponds to the date of the `ITK@nightly-master` commit

<sup>1</sup> To facilitate the update of the version, it could be added to a separate file like `itkVersion.py` or `itk/version.py`

**example of execution**

On unix:

```
# TODO: Delete old virtual env and create a new one (e.g name itk-nightly-wheel)

pip install scikit-ci-addons
git clone git://github.com/InsightSoftwareConsortium/ITKPythonPackage
cd ITKPythonPackage

platform=$(ci_addons publish_github_release --current-platform) # manylinux1, macosx or win
commit_date=$(ci_addons git --commit_date)

./scripts/dockcross-manylinux-build-wheels.sh && \
ci_addons publish_github_release  \
  --clear-pattern "*$platform*.whl" \
  --keep-pattern "*dev$commit_date*.whl" \
  InsightSoftwareConsortium/ITKPythonPackage \
  "dist/*dev$commit_date*$platform*.whl"
```

**Remarks:** Invocation of `ci_addons publish_github_release` should probably be moved into  `./scripts/dockcross-manylinux-build-wheels.sh` and `./scripts/macosx-build-wheels.sh`

On windows:

```
$PYTHON_DIR="C:/Python27-x64"
$env:PATH="$PYTHON_DIR;$PYTHON_DIR/Scripts;$env:PATH"

# TODO: Delete old virtual env and create a new one (e.g name itk-nightly-wheel)

pip install scikit-ci-addons
pip install ninja
git clone git://github.com/InsightSoftwareConsortium/ITKPythonPackage
cd ITKPythonPackage

$platform=(ci_addons publish_github_release --current-platform) # manylinux1, macosx or win
$commit_date=(ci_addons git --commit_date)

# Adapted from http://stackoverflow.com/questions/2251622/conditional-execution-and-in-powershell#7272878
$(python setup.py bdist_wheel | Out-Host;$?) -and `
$(
  ci_addons publish_github_release  `
    --clear-pattern "*$platform*.whl" `
    --keep-pattern "*dev$commit_date*.whl" `
    InsightSoftwareConsortium/ITKPythonPackage `
    "dist/*dev$commit_date*$platform*.whl"
| Out-Host;$?)
```

**Remarks:** Invocation of `ci_addons publish_github_release` should probably be moved into  `./scripts/windows-build-wheels.ps1`

**Comment by jcfr** [comment]
@thewtex Here is the workflow I envision for building and publishing the wheels

**Comment by thewtex** [comment]
@jcfr Fantastic! Yes!

A few suggested tweaks:

To obtain the version, we could use

```
git describe --tags --long
```

which will be simpler to obtain the base version and give additional details. The tag is then 

```
<major>.<minor>.<patch>.dev<YYYYMMDD>+<number_of_commits_since_tag>.<commit_short_hash>
```

inspired by [versioneer](https://www.python.org/dev/peps/pep-0427/) and compliant with [PEP 440](https://www.python.org/dev/peps/pep-0440/).

I think the `ci_addons publish_github_release` invocation should be moved to a machine secured to hold the upload token.

I will begin work on `upload_python_version.py`.

**Comment by blowekamp** [comment]
For SimpleITK We use the following format for versioning:

 <major>.<minor>.<patch>(.<tweak>).(post|pre)<number_of_commits_since_tag>(+g<commit_short_hash)

The optional `+g` is remove if `SimpleITK_BUILD_DISTRIBUTE` is true.

`post` is used if the current tag matches the the version defined in SimpleITK

**Comment by blowekamp** [comment]
Sorry! I ment to abandon my comment...

**Comment by jcfr** [comment]
Thanks for the review.

> To obtain the version, we could use `git describe --tags --long`:

This command returns `v4.11.0-124-g74035bf`, it means we will still have to retrieve the date

> I will begin work on upload_python_version.py.

Since I already have a local script for testing ... I propose instead to use it as a baseline.

**Comment by blowekamp** [comment]
You should look at the CMake scripts used in SimpleITK:

https://github.com/SimpleITK/SimpleITK/blob/master/CMake/sitkSourceVersion.cmake
https://github.com/SimpleITK/SimpleITK/blob/master/CMake/sitkSourceVersionVars.cmake.in

These inspect the SimpleITK repo to extract out this components along with the number of commits since the version file was modified. It also compare the tag version with the version in the version file to determine if the repo is "post" or "pre" release. This enables the release branch to be post, and the master branch to be pre. 

The current version of the SimpleITK master branch is "1.0.0.dev66", the release branch is "0.10.0.post3". There is the optional "+g#####" which is removed when SimpleITK_BUILD_DISTRIBUTE is defined; presumably defined only when on the official master or release branch.

The <number of commits> since version file was modified was chosen over the date because the number of commit is unique for the master/release branch, while there could be multiple commits on the same date. So with the SimpleITK version scheme the version is unique along the release/master branch without the `+g####`, while the above proposal requires it.

These CMake version file should be reusable in both ITK and SimpleITK.

**Comment by thewtex** [comment]
> This command returns v4.11.0-124-g74035bf, it means we will still have to retrieve the date

Yes, the proposed `git show` should work.

> Since I already have a local script for testing ... I propose instead to use it as a baseline.

Ok, the branch I am working on is here:

  https://github.com/thewtex/ITKPythonPackage/tree/nightly-version-script

@blowekamp The proposed format:

```
  <major>.<minor>.<patch>.dev<YYYYMMDD>+<number_of_commits_since_tag>.<commit_short_hash>
```

Is more informative and appropriate for the use case here, nightly builds.

**Comment by blowekamp** [comment]
What about: `<major>.<minor>.<patch>.dev<number_of_commits_since_tag>+<YYYYMMDD>.<commit_short_hash>` This would be a little more consistent with SimpleITK, and public identifier would uniquely describe the commit on the master branch without the [local identifier](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers).

If continuous or on demand packaging occurs the public identifier section would be sufficient to get the newest version.

**Comment by thewtex** [comment]
@blowekamp That sounds good to me.

**Comment by jcfr** [comment]
Closing. 

Add-on has been added.
See http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#publish-github-release-py

Companion project has also been updated.
See https://github.com/j0057/github-release
