### ISSUE TITLE
cmake_install should make use of CI caching

### ISSUE THREAD

**Issue by blowekamp** [scikit-build/scikit-ci-addons#49]
The cmake install by default downloads overtime. The default behavior should be use a download from the cache directory, if the download is not already cached it should download. The advantage of this is that it is generally faster, and improve reliability of the download source is temporarily unavailable.

**Comment by jcfr** [comment]
Caching was already possible on AppVeyor and Travis. This PR adds support for CirckeCI. See https://github.com/scikit-build/scikit-ci-addons/pull/58

**Comment by jcfr** [comment]
Closing. Fix integrated in https://github.com/scikit-build/scikit-ci-addons/commit/28f1ecb11df04015ba9cf2f22eb43320c2b7b1a1
