### ISSUE TITLE
[circle:install_cmake.py] add-on not supoorted on CircleCI 2.0 ?

### ISSUE THREAD

**Issue by blowekamp** [scikit-build/scikit-ci-addons#69]
On my SimpleITK CI on circleCI it just began getting the following error:

$ci_addons circle/install_cmake.py 3.10.2
[circle:install_cmake.py] add-on not supoorted on CircleCI 2.0

**Comment by jcfr** [comment]
Thanks for the report. Looking into it now.

For reference: https://circleci.com/gh/SimpleITK/SimpleITK/2442

**Comment by jcfr** [comment]
Issue is fixed in https://github.com/SimpleITK/SimpleITK/pull/534

**Comment by jcfr** [comment]
If (1) there are no wheels available for the version of CMake you want to install or (2) running CMake though a lightweight python wrapper is not desired, the add-on has been fixed to support CircleCI 2.0

See https://github.com/scikit-build/scikit-ci-addons/commit/64afcb128cf7366cc9a501cf6269140ce357e67e

**Comment by blowekamp** [comment]
The 64afcb1 patch should also throw an exception indicating the operation failed instead of successfully returning. Nice!

**Comment by jcfr** [comment]
> should also throw an exception indicating the operation failed instead of successfully returning.

Is the current implementation what you would expect ?

**Comment by blowekamp** [comment]
Yes, but I have not tried it out. 

Before the error message was written to the CircleCI output, but the step would be marked as successful, presumable since the return value from the process was still 0. I expect that the python exception would result is a failure return status from the command, and therefore would be marked as a failure for the CircleCI, which is my expected behavior.

**Comment by jcfr** [comment]
Indeed, it now work as expected. As demonstrated [here](https://circleci.com/gh/scikit-build/scikit-ci-addons/418?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) then fixed by https://github.com/scikit-build/scikit-ci-addons/commit/109334ddfb0351686df3558eb0326cc0d60ed2a9
